// nannies plate 1 of 1 -- GENERATED by nest.py
// 6 tags, shape-nested with rotation

translate([8.000, 12.763, 0]) rotate([0, 0, 0]) import("bite0.4/Nanny Sheila.stl");
translate([65.103, 84.943, 0]) rotate([0, 0, 315]) import("bite0.4/Nanny Gwen.stl");
translate([133.503, 56.718, 0]) rotate([0, 0, 315]) import("bite0.4/Graham.stl");
translate([173.103, 51.164, 0]) rotate([0, 0, 315]) import("bite0.4/Matt.stl");
translate([204.903, 52.642, 0]) rotate([0, 0, 315]) import("bite0.4/Grace.stl");
translate([12.903, 68.772, 0]) rotate([0, 0, 315]) import("bite0.4/Clara.stl");
