// nest plate 2 of 2 -- GENERATED by nest.py
// 3 tags, shape-nested with rotation

translate([8.000, 12.763, 0]) rotate([0, 0, 0]) import("bite0.4/Eileen.stl");
translate([39.903, 47.997, 0]) rotate([0, 0, 315]) import("bite0.4/Esma.stl");
translate([69.303, 44.520, 0]) rotate([0, 0, 315]) import("bite0.4/Tom.stl");
