// nest plate 1 of 2 -- GENERATED by nest.py
// 30 tags, shape-nested with rotation

translate([8.000, 12.763, 0]) rotate([0, 0, 0]) import("bite0.4/Nanny Sheila.stl");
translate([65.103, 84.943, 0]) rotate([0, 0, 315]) import("bite0.4/Nanny Gwen.stl");
translate([122.103, 67.825, 0]) rotate([0, 0, 315]) import("bite0.4/Veronique.stl");
translate([153.903, 69.077, 0]) rotate([0, 0, 315]) import("bite0.4/Harrison.stl");
translate([192.303, 62.935, 0]) rotate([0, 0, 315]) import("bite0.4/Marlow.stl");
translate([7.503, 78.627, 0]) rotate([0, 0, 315]) import("bite0.4/Grumpy.stl");
translate([93.631, 46.171, 0]) rotate([0, 0, 135]) import("bite0.4/Valentin.stl");
translate([191.703, 96.915, 0]) rotate([0, 0, 315]) import("bite0.4/Sebastien.stl");
translate([115.363, 129.690, 0]) rotate([0, 0, 270]) import("bite0.4/Graham.stl");
translate([143.103, 117.606, 0]) rotate([0, 0, 315]) import("bite0.4/Harry.stl");
translate([195.903, 124.391, 0]) rotate([0, 0, 315]) import("bite0.4/Frankie.stl");
translate([12.763, 143.844, 0]) rotate([0, 0, 270]) import("bite0.4/Gabby.stl");
translate([59.703, 135.646, 0]) rotate([0, 0, 315]) import("bite0.4/Corentin.stl");
translate([146.703, 158.161, 0]) rotate([0, 0, 315]) import("bite0.4/Quentin.stl");
translate([112.069, 110.000, 0]) rotate([0, 0, 90]) import("bite0.4/Justine.stl");
translate([45.163, 170.324, 0]) rotate([0, 0, 270]) import("bite0.4/Nicola.stl");
translate([202.503, 153.859, 0]) rotate([0, 0, 315]) import("bite0.4/Betty.stl");
translate([124.963, 184.236, 0]) rotate([0, 0, 270]) import("bite0.4/Matt.stl");
translate([41.723, 138.800, 0]) rotate([0, 0, 90]) import("bite0.4/Kaine.stl");
translate([199.869, 138.200, 0]) rotate([0, 0, 90]) import("bite0.4/Pascal.stl");
translate([72.763, 200.482, 0]) rotate([0, 0, 270]) import("bite0.4/Noah.stl");
translate([211.363, 212.640, 0]) rotate([0, 0, 270]) import("bite0.4/Grace.stl");
translate([154.363, 217.361, 0]) rotate([0, 0, 270]) import("bite0.4/Beth.stl");
translate([54.163, 227.165, 0]) rotate([0, 0, 270]) import("bite0.4/Robin.stl");
translate([103.963, 232.120, 0]) rotate([0, 0, 270]) import("bite0.4/Emilio.stl");
translate([145.386, 179.600, 0]) rotate([0, 0, 90]) import("bite0.4/Vicki.stl");
translate([12.763, 236.692, 0]) rotate([0, 0, 270]) import("bite0.4/Sacha.stl");
translate([180.763, 245.190, 0]) rotate([0, 0, 270]) import("bite0.4/Clara.stl");
translate([59.103, 233.812, 0]) rotate([0, 0, 315]) import("bite0.4/Mia.stl");
translate([209.703, 242.906, 0]) rotate([0, 0, 315]) import("bite0.4/Tali.stl");
