// plate 1 of 2 -- GENERATED by plate.py, do not edit
// 15 tags, Great Vibes 15mm, style=rail

translate([8.000, 12.763, 0]) import("tags/Marlow.stl");
translate([105.282, 12.763, 0]) import("tags/Valentin.stl");
translate([8.000, 47.954, 0]) import("tags/Frankie.stl");
translate([100.553, 47.954, 0]) import("tags/Harry.stl");
translate([8.000, 83.145, 0]) import("tags/Justine.stl");
translate([97.886, 83.145, 0]) import("tags/Corentin.stl");
translate([8.000, 118.336, 0]) import("tags/Grumpy.stl");
translate([96.928, 118.336, 0]) import("tags/Graham.stl");
translate([185.418, 118.336, 0]) import("tags/Seb.stl");
translate([8.000, 153.527, 0]) import("tags/Hazz.stl");
translate([93.802, 153.527, 0]) import("tags/Nicola.stl");
translate([179.126, 153.527, 0]) import("tags/Tom.stl");
translate([8.000, 188.717, 0]) import("tags/Quentin.stl");
translate([93.157, 188.717, 0]) import("tags/Pascal.stl");
translate([177.647, 188.717, 0]) import("tags/Grace.stl");
