// plate 1 of 2 -- GENERATED by plate.py, do not edit
// 19 tags, Great Vibes 15mm, style=lift

translate([8.000, 12.763, 0]) import("tags/Matt.stl");
translate([70.636, 12.763, 0]) import("tags/Mia.stl");
translate([126.835, 12.763, 0]) import("tags/Pascal.stl");
translate([193.325, 12.763, 0]) import("tags/Grace.stl");
translate([8.000, 47.183, 0]) import("tags/Noah.stl");
translate([68.282, 47.183, 0]) import("tags/Tali.stl");
translate([119.523, 47.183, 0]) import("tags/Kaine.stl");
translate([184.555, 47.183, 0]) import("tags/Eileen.stl");
translate([8.000, 81.604, 0]) import("tags/Betty.stl");
translate([69.074, 81.604, 0]) import("tags/Nicola.stl");
translate([136.397, 81.604, 0]) import("tags/Gabby.stl");
translate([198.242, 81.604, 0]) import("tags/Tom.stl");
translate([8.000, 116.024, 0]) import("tags/Beth.stl");
translate([64.761, 116.024, 0]) import("tags/Sheila.stl");
translate([128.382, 116.024, 0]) import("tags/Quentin.stl");
translate([195.539, 116.024, 0]) import("tags/Vero.stl");
translate([8.000, 150.444, 0]) import("tags/Graham.stl");
translate([78.490, 150.444, 0]) import("tags/Justine.stl");
translate([150.376, 150.444, 0]) import("tags/Robin.stl");
