// plate 2 of 2 -- GENERATED by plate.py, do not edit
// 14 tags, Great Vibes 15mm, style=lift

translate([8.000, 12.763, 0]) import("tags/Gwen.stl");
translate([64.115, 12.763, 0]) import("tags/Vicki.stl");
translate([122.626, 12.763, 0]) import("tags/Grumpy.stl");
translate([193.554, 12.763, 0]) import("tags/Clara.stl");
translate([8.000, 47.183, 0]) import("tags/Emilio.stl");
translate([71.720, 47.183, 0]) import("tags/Hazz.stl");
translate([139.522, 47.183, 0]) import("tags/Esma.stl");
translate([197.679, 47.183, 0]) import("tags/Seb.stl");
translate([8.000, 81.604, 0]) import("tags/Valentin.stl");
translate([85.324, 81.604, 0]) import("tags/Corentin.stl");
translate([157.127, 81.604, 0]) import("tags/Harry.stl");
translate([8.000, 116.024, 0]) import("tags/Sacha.stl");
translate([70.892, 116.024, 0]) import("tags/Marlow.stl");
translate([150.174, 116.024, 0]) import("tags/Frankie.stl");
