// plate 1 of 2 -- GENERATED by plate.py, do not edit
// 18 tags, Great Vibes 15mm, style=rail

translate([8.000, 15.000, 0]) import("tags/Kaine.stl");
translate([92.228, 15.000, 0]) import("tags/Pascal.stl");
translate([177.915, 15.000, 0]) import("tags/Seb.stl");
translate([8.000, 52.427, 0]) import("tags/Mia.stl");
translate([83.395, 52.427, 0]) import("tags/Robin.stl");
translate([164.957, 52.427, 0]) import("tags/Gabby.stl");
translate([8.000, 89.854, 0]) import("tags/Hazz.stl");
translate([94.999, 89.854, 0]) import("tags/Emilio.stl");
translate([177.915, 89.854, 0]) import("tags/Tali.stl");
translate([8.000, 127.281, 0]) import("tags/Vero.stl");
translate([82.500, 127.281, 0]) import("tags/Frankie.stl");
translate([176.249, 127.281, 0]) import("tags/Grace.stl");
translate([8.000, 164.708, 0]) import("tags/Quentin.stl");
translate([94.354, 164.708, 0]) import("tags/Gwen.stl");
translate([169.665, 164.708, 0]) import("tags/Eileen.stl");
translate([8.000, 202.135, 0]) import("tags/Matt.stl");
translate([89.833, 202.135, 0]) import("tags/Vicki.stl");
translate([167.541, 202.135, 0]) import("tags/Sheila.stl");
