// plate 2 of 2 -- GENERATED by plate.py, do not edit
// 15 tags, Great Vibes 15mm, style=rail

translate([8.000, 15.000, 0]) import("tags/Marlow.stl");
translate([106.478, 15.000, 0]) import("tags/Valentin.stl");
translate([8.000, 52.427, 0]) import("tags/Clara.stl");
translate([84.187, 52.427, 0]) import("tags/Noah.stl");
translate([163.665, 52.427, 0]) import("tags/Sacha.stl");
translate([8.000, 89.854, 0]) import("tags/Justine.stl");
translate([99.083, 89.854, 0]) import("tags/Graham.stl");
translate([8.000, 127.281, 0]) import("tags/Esma.stl");
translate([85.354, 127.281, 0]) import("tags/Corentin.stl");
translate([176.353, 127.281, 0]) import("tags/Tom.stl");
translate([8.000, 164.708, 0]) import("tags/Beth.stl");
translate([83.957, 164.708, 0]) import("tags/Nicola.stl");
translate([170.477, 164.708, 0]) import("tags/Betty.stl");
translate([8.000, 202.135, 0]) import("tags/Harry.stl");
translate([99.791, 202.135, 0]) import("tags/Grumpy.stl");
