// plate 2 of 2 -- GENERATED by plate.py, do not edit
// 18 tags, Great Vibes 15mm, style=rail

translate([8.000, 12.763, 0]) import("tags/Kaine.stl");
translate([91.032, 12.763, 0]) import("tags/Emilio.stl");
translate([172.752, 12.763, 0]) import("tags/Betty.stl");
translate([8.000, 47.954, 0]) import("tags/Sheila.stl");
translate([89.621, 47.954, 0]) import("tags/Sacha.stl");
translate([170.513, 47.954, 0]) import("tags/Matt.stl");
translate([8.000, 83.145, 0]) import("tags/Robin.stl");
translate([88.365, 83.145, 0]) import("tags/Gabby.stl");
translate([168.210, 83.145, 0]) import("tags/Eileen.stl");
translate([8.000, 118.336, 0]) import("tags/Noah.stl");
translate([86.282, 118.336, 0]) import("tags/Vicki.stl");
translate([162.794, 118.336, 0]) import("tags/Esma.stl");
translate([8.000, 153.527, 0]) import("tags/Clara.stl");
translate([82.990, 153.527, 0]) import("tags/Beth.stl");
translate([157.751, 153.527, 0]) import("tags/Mia.stl");
translate([8.000, 188.717, 0]) import("tags/Gwen.stl");
translate([82.115, 188.717, 0]) import("tags/Vero.stl");
translate([155.418, 188.717, 0]) import("tags/Tali.stl");
