// TEST PLATE -- GENERATED by testplate.py, do not edit
// left column: v1, clip in the letter plane (hangs on the side)
// right column: v2, clip out of plane (hangs on the front)

translate([8.000, 12.763, 0]) import("bite0.4/Justine.stl");
translate([81.886, 33.469, 0]) import("../../glass-name-tag-back/export/Justine.stl");
translate([8.000, 48.996, 0]) import("bite0.4/Quentin.stl");
translate([77.157, 69.139, 0]) import("../../glass-name-tag-back/export/Quentin.stl");
translate([8.000, 84.666, 0]) import("bite0.4/Grumpy.stl");
translate([80.928, 105.559, 0]) import("../../glass-name-tag-back/export/Grumpy.stl");
translate([8.000, 121.086, 0]) import("bite0.4/Harrison.stl");
translate([97.969, 137.438, 0]) import("../../glass-name-tag-back/export/Harrison.stl");
translate([8.000, 152.965, 0]) import("bite0.4/Vicki.stl");
translate([68.512, 168.587, 0]) import("../../glass-name-tag-back/export/Vicki.stl");
translate([8.000, 184.114, 0]) import("bite0.4/Tali.stl");
translate([61.241, 197.508, 0]) import("../../glass-name-tag-back/export/Tali.stl");
