#!/usr/bin/env python3
"""One test plate: the hardest names, in BOTH variants, side by side.

  v1 (side clip)  left column   -- clip curls in the letter plane, hangs edge-on
  v2 (back clip)  right column  -- clip curls out of plane, hangs face-on

One name per row so the two are directly comparable. The names are chosen by
measurement, not taste -- between them they cover every way a name has broken
this model:

  Justine   deepest tails (8.11mm) AND 2 pieces to weld AND long
  Quentin   most pieces to weld (3 struts)
  Grumpy    deep p and y tails together
  Harrison  longest in the set (72.6mm of ink) -- and one of the three
            renamed names, so it gets checked in the flesh
  Vicki     two i-dots but almost no descender -- the case that used to float
            clear of the bar and print as loose letters
  Tali      shortest (35.8mm) -- the other end of the range

Both variants are already exported in their print orientation: v1 flat, v2
letters-down with the clip standing up. This only lays them out.
"""
import os
import subprocess
import sys

import bridges

HERE = os.path.dirname(os.path.abspath(__file__))
V2 = os.path.join(os.path.dirname(HERE), "glass-name-tag-back", "export")
V1 = os.path.join(HERE, "export", "bite0.4")
OUT = os.path.join(HERE, "export")
PREV = os.path.join(HERE, "previews")
OPENSCAD = os.environ.get("OSCAD", "openscad")

NAMES = ["Justine", "Quentin", "Grumpy", "Harrison", "Vicki", "Tali"]
BED = float(os.environ.get("BED", 256))
MARGIN = float(os.environ.get("MARGIN", 8))
GAP = float(os.environ.get("GAP", 6))       # a bit more, so they snip apart easily


def box(path):
    v = bridges.load_tris(path).reshape(-1, 3)
    return (float(v[:, 0].min()), float(v[:, 1].min()),
            float(v[:, 0].max()), float(v[:, 1].max()), float(v[:, 2].min()),
            float(v[:, 2].max()))


def main():
    missing = [(v, n) for v, d in (("v1", V1), ("v2", V2)) for n in NAMES
               if not os.path.exists(os.path.join(d, f"{n}.stl"))]
    if missing:
        raise SystemExit(f"missing exports: {missing}")

    rows, y = [], 0.0
    lines = ["// TEST PLATE -- GENERATED by testplate.py, do not edit",
             "// left column: v1, clip in the letter plane (hangs on the side)",
             "// right column: v2, clip out of plane (hangs on the front)", ""]
    print(f"{'name':10} {'v1 w x h':>14} {'v2 w x h':>14} {'row width':>10}")
    print("-" * 54)
    for n in NAMES:
        b1, b2 = box(os.path.join(V1, f"{n}.stl")), box(os.path.join(V2, f"{n}.stl"))
        w1, h1 = b1[2] - b1[0], b1[3] - b1[1]
        w2, h2 = b2[2] - b2[0], b2[3] - b2[1]
        for b in (b1, b2):
            if abs(b[4]) > 1e-6:
                raise SystemExit(f"{n} sits {b[4]:.2f}mm off the bed")
        lines.append(f'translate([{MARGIN - b1[0]:.3f}, {MARGIN + y - b1[1]:.3f}, 0])'
                     f' import("bite0.4/{n}.stl");')
        x2 = MARGIN + w1 + GAP
        lines.append(f'translate([{x2 - b2[0]:.3f}, {MARGIN + y - b2[1]:.3f}, 0])'
                     f' import("../../glass-name-tag-back/export/{n}.stl");')
        print(f"{n:10} {w1:6.1f} x {h1:5.1f} {w2:6.1f} x {h2:5.1f} {w1+GAP+w2:10.1f}")
        rows.append(w1 + GAP + w2)
        y += max(h1, h2) + GAP

    usable = BED - 2 * MARGIN
    if max(rows) > usable or y - GAP > usable:
        raise SystemExit(f"does not fit: {max(rows):.0f} x {y-GAP:.0f} in {usable:.0f}")
    print("-" * 54)
    print(f"plate uses {max(rows):.0f} x {y-GAP:.0f}mm of {usable:.0f}x{usable:.0f}")

    scad = os.path.join(OUT, "testplate.scad")
    with open(scad, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    for args, out in ((["--enable=lazy-union"], "testplate.3mf"),
                      (["--export-format", "binstl"], "testplate.stl")):
        subprocess.run([OPENSCAD, "-o", os.path.join(OUT, out)] + args + [scad],
                       capture_output=True)
    subprocess.run([OPENSCAD, "-o", os.path.join(PREV, "testplate.png"),
                    "--camera=0,0,0,0,0,0,0", "--viewall", "--autocenter", "--render",
                    "--colorscheme=Tomorrow", "--imgsize=1100,1000", scad],
                   capture_output=True)
    print("\nwrote export/testplate.3mf (+ .stl) and previews/testplate.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
