#!/usr/bin/env python3
"""Pack variant 2 onto build plates.

Same packing as variant 1 -- first-fit decreasing plus seeded random restarts,
then rows spread evenly over plates -- reusing that module rather than a second
copy of the algorithm.

The one thing that differs, and it matters: these are exported by `build.py` as
`part="print"`, which is the tag rolled LETTERS DOWN. That orientation is not
optional here. The clip stands off the back of the letter plane, so letters-up
would put the clip on the bed and float the whole name in the air. It is also
what you want anyway: the glass sits on the clip's side, so the face that reads
to the room is the face on the build plate -- the smooth one.
"""
import json
import os
import re
import shutil
import subprocess
import sys

import numpy as np

V1 = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                  "glass-name-tag")
sys.path.insert(0, V1)
import bridges                      # noqa: E402
import plate as v1plate             # noqa: E402  (for shelf_pack)

HERE = os.path.dirname(os.path.abspath(__file__))
EXPORT = os.path.join(HERE, "export")
PREV = os.path.join(HERE, "previews")
OPENSCAD = os.environ.get("OSCAD", "openscad")

BED = float(os.environ.get("BED", 256))
MARGIN = float(os.environ.get("MARGIN", 8))


def main():
    names = [l.strip() for l in open(os.path.join(V1, "names.txt")) if l.strip()]
    missing = [n for n in names if not os.path.exists(os.path.join(EXPORT, f"{n}.stl"))]
    if missing:
        raise SystemExit(f"run `make export` first -- missing: {missing[:5]}")

    # stale plates must not survive a run that needs fewer of them
    for d, exts in ((EXPORT, ("3mf", "stl", "scad")), (PREV, ("png",))):
        for f in (os.listdir(d) if os.path.isdir(d) else []):
            if f.startswith("plate") and f.rsplit(".", 1)[-1] in exts:
                os.remove(os.path.join(d, f))

    boxes, items = {}, []
    for n in names:
        v = bridges.load_tris(os.path.join(EXPORT, f"{n}.stl")).reshape(-1, 3)
        boxes[n] = (float(v[:, 0].min()), float(v[:, 1].min()),
                    float(v[:, 0].max()), float(v[:, 1].max()))
        zmin = float(v[:, 2].min())
        if abs(zmin) > 1e-6:
            raise SystemExit(f"{n}: sits {zmin:.2f}mm off the bed, not flat on it")
        items.append((n, boxes[n][2] - boxes[n][0], boxes[n][3] - boxes[n][1]))

    usable = BED - 2 * MARGIN
    plates = v1plate.shelf_pack(items, usable, usable)
    dims = {n: (w, h) for n, w, h in items}

    print(f"{len(names)} tags, letters DOWN, bed {BED:g}mm")
    print(f"packed onto {len(plates)} plate(s), {usable:g}x{usable:g}mm usable:")
    for pi, plate in enumerate(plates, 1):
        used = sum(dims[n][0] * dims[n][1] for n, _, _ in plate)
        print(f"  plate {pi}: {len(plate):2d} tags, {100*used/(usable*usable):4.1f}% area")
        lines = [f"// plate {pi} of {len(plates)} -- GENERATED by plate.py, do not edit",
                 f"// {len(plate)} tags, letters face DOWN (see the module docstring)", ""]
        for n, x, y in plate:
            bx0, by0, _, _ = boxes[n]
            lines.append(f'translate([{x - bx0 + MARGIN:.3f}, {y - by0 + MARGIN:.3f}, 0])'
                         f' import("{n}.stl");')
        scad = os.path.join(EXPORT, f"plate{pi}.scad")
        with open(scad, "w") as fh:
            fh.write("\n".join(lines) + "\n")
        subprocess.run([OPENSCAD, "-o", os.path.join(EXPORT, f"plate{pi}.3mf"),
                        "--enable=lazy-union", scad], capture_output=True)
        subprocess.run([OPENSCAD, "-o", os.path.join(PREV, f"plate{pi}.png"),
                        "--camera=0,0,0,0,0,0,0", "--viewall", "--autocenter",
                        "--render", "--colorscheme=Tomorrow", "--imgsize=1000,1000",
                        scad], capture_output=True)
    print(f"\nwrote export/plate1..{len(plates)}.3mf and previews/plate*.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
