// nest plate 1 of 1 -- GENERATED by nest.py
// 33 tags, shape-nested with rotation

translate([8.000, 32.407, 0]) rotate([0, 0, 0]) import("./Veronique.stl");
translate([118.375, 7.503, 0]) rotate([0, 0, 135]) import("./Harrison.stl");
translate([152.432, 7.503, 0]) rotate([0, 0, 135]) import("./Marlow.stl");
translate([184.325, 7.503, 0]) rotate([0, 0, 135]) import("./Grumpy.stl");
translate([224.816, 7.503, 0]) rotate([0, 0, 135]) import("./Graham.stl");
translate([247.257, 102.316, 0]) rotate([0, 0, 270]) import("./Sebastien.stl");
translate([7.503, 41.971, 0]) rotate([0, 0, 45]) import("./Valentin.stl");
translate([224.504, 41.703, 0]) rotate([0, 0, 135]) import("./Harry.stl");
translate([172.488, 45.903, 0]) rotate([0, 0, 135]) import("./Frankie.stl");
translate([54.105, 92.702, 0]) rotate([0, 0, 225]) import("./Gabby.stl");
translate([104.163, 104.293, 0]) rotate([0, 0, 315]) import("./Quentin.stl");
translate([89.269, 131.086, 0]) rotate([0, 0, 270]) import("./Justine.stl");
translate([173.520, 143.603, 0]) rotate([0, 0, 270]) import("./Corentin.stl");
translate([222.577, 80.703, 0]) rotate([0, 0, 135]) import("./Nicola.stl");
translate([52.720, 131.157, 0]) rotate([0, 0, 225]) import("./Betty.stl");
translate([153.862, 90.303, 0]) rotate([0, 0, 135]) import("./Matt.stl");
translate([236.556, 99.303, 0]) rotate([0, 0, 135]) import("./Kaine.stl");
translate([89.322, 140.387, 0]) rotate([0, 0, 225]) import("./Pascal.stl");
translate([109.925, 162.082, 0]) rotate([0, 0, 270]) import("./Noah.stl");
translate([148.740, 126.903, 0]) rotate([0, 0, 135]) import("./Grace.stl");
translate([245.457, 183.421, 0]) rotate([0, 0, 270]) import("./Sheila.stl");
translate([49.744, 165.451, 0]) rotate([0, 0, 225]) import("./Gwen.stl");
translate([187.432, 186.965, 0]) rotate([0, 0, 270]) import("./Robin.stl");
translate([90.597, 171.308, 0]) rotate([0, 0, 225]) import("./Beth.stl");
translate([217.332, 200.320, 0]) rotate([0, 0, 270]) import("./Emilio.stl");
translate([166.386, 207.712, 0]) rotate([0, 0, 270]) import("./Vicki.stl");
translate([130.607, 195.510, 0]) rotate([0, 0, 225]) import("./Mia.stl");
translate([57.057, 219.892, 0]) rotate([0, 0, 270]) import("./Sacha.stl");
translate([98.767, 209.870, 0]) rotate([0, 0, 225]) import("./Clara.stl");
translate([8.000, 168.200, 0]) rotate([0, 0, 90]) import("./Eileen.stl");
translate([82.841, 35.000, 0]) rotate([0, 0, 180]) import("./Tali.stl");
translate([143.532, 221.157, 0]) rotate([0, 0, 270]) import("./Esma.stl");
translate([219.800, 170.000, 0]) rotate([0, 0, 90]) import("./Tom.stl");
