// plate 2 of 2 -- GENERATED by plate.py, do not edit
// 18 tags, letters face DOWN (see the module docstring)

translate([8.000, 26.532, 0]) import("Emilio.stl");
translate([71.720, 27.657, 0]) import("Sheila.stl");
translate([135.341, 27.657, 0]) import("Sacha.stl");
translate([198.233, 26.157, 0]) import("Tom.stl");
translate([8.000, 57.765, 0]) import("Matt.stl");
translate([70.636, 55.689, 0]) import("Robin.stl");
translate([133.002, 63.313, 0]) import("Gabby.stl");
translate([194.846, 57.376, 0]) import("Clara.stl");
translate([8.000, 91.074, 0]) import("Betty.stl");
translate([69.074, 85.845, 0]) import("Eileen.stl");
translate([129.689, 87.638, 0]) import("Noah.stl");
translate([189.971, 87.699, 0]) import("Vicki.stl");
translate([8.000, 115.502, 0]) import("Esma.stl");
translate([66.157, 116.085, 0]) import("Beth.stl");
translate([122.918, 122.627, 0]) import("Grace.stl");
translate([179.158, 117.078, 0]) import("Mia.stl");
translate([8.000, 152.283, 0]) import("Gwen.stl");
translate([64.115, 144.784, 0]) import("Tali.stl");
