// plate 1 of 2 -- GENERATED by plate.py, do not edit
// 15 tags, letters face DOWN (see the module docstring)

translate([8.000, 29.115, 0]) import("Harrison.stl");
translate([95.969, 32.407, 0]) import("Veronique.stl");
translate([182.168, 28.325, 0]) import("Nicola.stl");
translate([8.000, 57.314, 0]) import("Sebastien.stl");
translate([89.516, 57.765, 0]) import("Marlow.stl");
translate([168.798, 58.043, 0]) import("Valentin.stl");
translate([8.000, 85.595, 0]) import("Frankie.stl");
translate([82.553, 91.470, 0]) import("Harry.stl");
translate([155.147, 92.782, 0]) import("Justine.stl");
translate([8.000, 116.689, 0]) import("Corentin.stl");
translate([79.803, 122.627, 0]) import("Grumpy.stl");
translate([150.731, 122.627, 0]) import("Graham.stl");
translate([8.000, 151.533, 0]) import("Quentin.stl");
translate([75.157, 145.096, 0]) import("Pascal.stl");
translate([141.647, 148.950, 0]) import("Kaine.stl");
